import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import styles from "@/styles/Home.module.css";
import Card from "@/components/Card";
import Typography from "@/components/Typography";
import Navbar from "@/components/Navbar";
import Heading from "@/components/Heading";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const datas = [
  {
    title: "Software development",
    desc: "Software development refers to a set of computer science activities dedicated to the process of creating, designing, deploying and supporting software. Software itself is the set of instructions or programs that tell a computer what to do.",
    img: "/images/photo-1519389950473-47ba0277781c.avif",
    profile: ["favicon.svg", "Anna", "April 21, 2023"],
  },
  {
    title: "Software development",
    desc: "Software development refers to a set of computer science activities dedicated to the process of creating, designing, deploying and supporting software. Software itself is the set of instructions or programs that tell a computer what to do.",
    img: "/images/photo-1519389950473-47ba0277781c.avif",
    profile: ["favicon.svg", "Anna", "April 21, 2023"],
  },
  {
    title: "Software development",
    desc: "Software development refers to a set of computer science activities dedicated to the process of creating, designing, deploying and supporting software. Software itself is the set of instructions or programs that tell a computer what to do.",
    img: "./images/photo-1519389950473-47ba0277781c.avif",
    profile: ["favicon.svg", "Anna", "April 21, 2023"],
  },
  {
    title: "Software development",
    desc: "Software development refers to a set of computer science activities dedicated to the process of creating, designing, deploying and supporting software. Software itself is the set of instructions or programs that tell a computer what to do.",
    img: "./images/photo-1519389950473-47ba0277781c.avif",
    profile: ["favicon.svg", "Anna", "April 21, 2023"],
  },
  {
    title: "Software development",
    desc: "Software development refers to a set of computer science activities dedicated to the process of creating, designing, deploying and supporting software. Software itself is the set of instructions or programs that tell a computer what to do.",
    img: "./images/photo-1519389950473-47ba0277781c.avif",
    profile: ["favicon.svg", "Anna", "April 21, 2023"],
  },
  {
    title: "Software development",
    desc: "Software development refers to a set of computer science activities dedicated to the process of creating, designing, deploying and supporting software. Software itself is the set of instructions or programs that tell a computer what to do.",
    img: "./images/photo-1519389950473-47ba0277781c.avif",
    profile: ["favicon.svg", "Anna", "April 21, 2023"],
  },
  {
    title: "Software development",
    desc: "Software development refers to a set of computer science activities dedicated to the process of creating, designing, deploying and supporting software. Software itself is the set of instructions or programs that tell a computer what to do.",
    img: "./images/photo-1519389950473-47ba0277781c.avif",
    profile: ["favicon.svg", "Anna", "April 21, 2023"],
  },
  {
    title: "Software development",
    desc: "Software development refers to a set of computer science activities dedicated to the process of creating, designing, deploying and supporting software. Software itself is the set of instructions or programs that tell a computer what to do.",
    img: "./images/photo-1519389950473-47ba0277781c.avif",
    profile: ["favicon.svg", "Anna", "April 21, 2023"],
  },
];
export default function Home() {
  return (
    <>
      <Head>
        <title>Blog post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.lightGray} ${inter.className}`}>
        <div className="container">
          {/* <Navbar /> */}
          <div className="titleSection">
            <Heading text="Blog posts" />
            <Typography text="Our latest updates and blogs about managing your team" />
          </div>

          <div className="cards">
            {datas.map((data, index) => (
              <Card item={data} key={index} />
            ))}
          </div>
          {/* <Footer /> */}
        </div>
      </main>
    </>
  );
}
